import datetime

SHIFT_START_TIME = datetime.time(6, 0)   
SHIFT_END_TIME = datetime.time(3, 0) 
DRIVER_A_OBED_HOURS = 4
DRIVER_A_LUNCH_MINUTES = 60
DRIVER_A_WORK_HOURS = 8
DRIVER_B_WORK_HOURS = 12
DRIVER_B_BREAK_FREQUENCY = 120
DRIVER_B_LONG_BREAK_MINUTES = 40
ROUTE_TIME_MIN_MINUTES = 65
ROUTE_TIME_MAX_MINUTES = 75
PEAK_PASSENGER_PERCENT = 0.7

POPULATION_SIZE = 50
GENERATIONS = 30
MUTATION_RATE = 0.1

PEAK_HOURS_START_1 = datetime.time(7, 0)
PEAK_HOURS_END_1   = datetime.time(9, 0)
PEAK_HOURS_START_2 = datetime.time(17, 0)
PEAK_HOURS_END_2   = datetime.time(19, 0)

WEEKEND = ["Saturday", "Sunday"]

SHIFT_CHANGE_TIME_MIN = 10
SHIFT_CHANGE_TIME_MAX = 15
